from agenteval.config import (
    OPENNESS_OPEN_SOURCE_OPEN_WEIGHTS as CANONICAL_OPENNESS_OPEN_SOURCE_OPEN_WEIGHTS,
    OPENNESS_OPEN_SOURCE_CLOSED_WEIGHTS as CANONICAL_OPENNESS_OPEN_SOURCE_CLOSED_WEIGHTS,
    OPENNESS_CLOSED_API_AVAILABLE as CANONICAL_OPENNESS_CLOSED_API_AVAILABLE,
    OPENNESS_CLOSED_UI_ONLY as CANONICAL_OPENNESS_CLOSED_UI_ONLY,
    TOOL_USAGE_STANDARD as CANONICAL_TOOL_USAGE_STANDARD,
    TOOL_USAGE_CUSTOM_INTERFACE as CANONICAL_TOOL_USAGE_CUSTOM_INTERFACE,
    TOOL_USAGE_FULLY_CUSTOM as CANONICAL_TOOL_USAGE_FULLY_CUSTOM,
)


OPENNESS_ALIASES = {
    CANONICAL_OPENNESS_OPEN_SOURCE_OPEN_WEIGHTS: {"Open Source + Open Weights"},
    CANONICAL_OPENNESS_OPEN_SOURCE_CLOSED_WEIGHTS: {"Open Source"},
    CANONICAL_OPENNESS_CLOSED_API_AVAILABLE: {"API Available"},
    CANONICAL_OPENNESS_CLOSED_UI_ONLY: {"Closed"}
}

TOOL_USAGE_ALIASES = {
    CANONICAL_TOOL_USAGE_STANDARD: {},
    CANONICAL_TOOL_USAGE_CUSTOM_INTERFACE: {"Custom with Standard Search"},
    CANONICAL_TOOL_USAGE_FULLY_CUSTOM: {"Fully Custom"}
}
