CANONICAL_OPENNESS_OPEN_SOURCE_OPEN_WEIGHTS = "Open Source + Open Weights"
CANONICAL_OPENNESS_OPEN_SOURCE_CLOSED_WEIGHTS = "Open Source"
CANONICAL_OPENNESS_CLOSED_API_AVAILABLE = "API Available"
CANONICAL_OPENNESS_CLOSED_UI_ONLY = "Closed"


CANONICAL_TOOL_USAGE_STANDARD = "Standard"
CANONICAL_TOOL_USAGE_CUSTOM_INTERFACE = "Custom with Standard Search"
CANONICAL_TOOL_USAGE_FULLY_CUSTOM = "Fully Custom"


OPENNESS_ALIASES = {
    CANONICAL_OPENNESS_OPEN_SOURCE_OPEN_WEIGHTS: {"Open source & open weights"},
    CANONICAL_OPENNESS_OPEN_SOURCE_CLOSED_WEIGHTS: {"Open source & closed weights"},
    CANONICAL_OPENNESS_CLOSED_API_AVAILABLE: {"Closed source & API available"},
    CANONICAL_OPENNESS_CLOSED_UI_ONLY: {"Closed source & UI only"}
}

TOOL_USAGE_ALIASES = {
    CANONICAL_TOOL_USAGE_STANDARD: {},
    CANONICAL_TOOL_USAGE_CUSTOM_INTERFACE: {"Custom interface"},
    CANONICAL_TOOL_USAGE_FULLY_CUSTOM: {"Fully custom"}
}
